/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Patients */
        get: operations["list_patients_patients_get"];
        put?: never;
        /** Create Patient */
        post: operations["create_patient_patients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{patient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Patient */
        get: operations["get_patient_patients__patient_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Patient */
        patch: operations["update_patient_patients__patient_id__patch"];
        trace?: never;
    };
    "/encounters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Encounters */
        get: operations["list_encounters_encounters_get"];
        put?: never;
        /** Create Encounter */
        post: operations["create_encounter_encounters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{encounter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Encounter */
        get: operations["get_encounter_encounters__encounter_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{encounter_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start */
        post: operations["start_encounters__encounter_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{encounter_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause */
        post: operations["pause_encounters__encounter_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{encounter_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume */
        post: operations["resume_encounters__encounter_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{encounter_id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish
         * @description Fin de l'écoute puis traitement. 409 AUDIO_CHUNKS_MISSING s'il manque des segments.
         */
        post: operations["finish_encounters__encounter_id__finish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{encounter_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Progress
         * @description Où en est le traitement, d'après la base — jamais une progression inventée (S06).
         */
        get: operations["read_progress_encounters__encounter_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{encounter_id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process
         * @description Relance du traitement après une erreur ; sans effet si déjà traité.
         */
        post: operations["process_encounters__encounter_id__process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{encounter_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Encounter */
        post: operations["validate_encounter_encounters__encounter_id__validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{encounter_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transcript */
        get: operations["transcript_encounters__encounter_id__transcript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{encounter_id}/clinical-object": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clinical Object */
        get: operations["clinical_object_encounters__encounter_id__clinical_object_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Correct Clinical Object */
        patch: operations["correct_clinical_object_encounters__encounter_id__clinical_object_patch"];
        trace?: never;
    };
    "/encounters/{encounter_id}/corrections/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Correct From Speech
         * @description Correction dictée ou écrite : aperçu du patch, puis application sur confirmation.
         *
         *     Rien n'est deviné : une commande ambiguë revient au praticien avec la raison.
         */
        post: operations["correct_from_speech_encounters__encounter_id__corrections_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{encounter_id}/corrections/voice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Correct From Voice
         * @description Correction dictée au micro : transcrite, interprétée, jamais conservée.
         *
         *     L'audio d'une correction ne traverse pas le stockage : il est transcrit dans la
         *     requête, puis oublié (D010).
         */
        post: operations["correct_from_voice_encounters__encounter_id__corrections_voice_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{encounter_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_encounters__encounter_id__documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{encounter_id}/documents/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Documents */
        post: operations["generate_documents_encounters__encounter_id__documents_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{encounter_id}/documents/operative-note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Operative Note
         * @description Compte rendu de soins, à la demande du praticien (§81) : jamais d'office.
         */
        post: operations["generate_operative_note_encounters__encounter_id__documents_operative_note_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Document */
        post: operations["validate_document_documents__document_id__validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Document
         * @description Sortie d'un document : PDF à imprimer, ou texte à coller dans le logiciel métier.
         */
        get: operations["export_document_documents__document_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{encounter_id}/learning-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Learning Events */
        get: operations["learning_events_encounters__encounter_id__learning_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/synthetic-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cases */
        get: operations["list_cases_synthetic_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/synthetic-cases/{case_id}/encounters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Case
         * @description Consultation complète en un appel : patient fictif, démarrage, fin, traitement.
         */
        post: operations["run_case_synthetic_cases__case_id__encounters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{encounter_id}/audio/chunks/{sequence}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Chunk
         * @description Idempotent : renvoyer le même segment est sans effet.
         */
        put: operations["put_chunk_encounters__encounter_id__audio_chunks__sequence__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{encounter_id}/audio/gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report Gap */
        post: operations["report_gap_encounters__encounter_id__audio_gaps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{encounter_id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Audio */
        get: operations["get_audio_encounters__encounter_id__audio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/client": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Client Config */
        get: operations["client_config_config_client_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ontology/concepts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Concepts
         * @description Vocabulaire d'Oris : code technique -> mot français.
         *
         *     L'interface ne doit jamais montrer `cold_sensitivity` à un praticien.
         */
        get: operations["read_concepts_ontology_concepts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Preferences */
        get: operations["read_preferences_me_preferences_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Preferences
         * @description Ne change que la forme des documents ; le dossier clinique n'est pas touché.
         */
        patch: operations["patch_preferences_me_preferences_patch"];
        trace?: never;
    };
    "/glossary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Glossary */
        get: operations["list_glossary_glossary_get"];
        put?: never;
        /** Add Glossary Term */
        post: operations["add_glossary_term_glossary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/glossary/{term_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Glossary Term
         * @description Corriger un terme, ou le désactiver : l'apprentissage doit être réversible.
         */
        patch: operations["patch_glossary_term_glossary__term_id__patch"];
        trace?: never;
    };
    "/me/learning/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Suggestions
         * @description Habitudes constatées, proposées au praticien. Rien n'est appliqué d'office.
         */
        get: operations["list_suggestions_me_learning_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Audit
         * @description Qui a fait quoi, quand. Réservé aux consultations de l'organisation du praticien.
         */
        get: operations["read_audit_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maintenance/audio-purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Audio Purge
         * @description Repasse la purge du son sur les consultations déjà traitées. Rejouable sans risque.
         */
        post: operations["run_audio_purge_maintenance_audio_purge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddFact */
        AddFact: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            operation: "add_fact";
            fact: components["schemas"]["NewFact"];
        };
        /** AudioGapOut */
        AudioGapOut: {
            /** Duration Ms */
            duration_ms: number | null;
        };
        /** AudioGapReport */
        AudioGapReport: {
            /**
             * Reason
             * @enum {string}
             */
            reason: "microphone_lost" | "page_reloaded" | "capture_error" | "audio_interruption" | "route_change" | "app_terminated";
            /** Duration Ms */
            duration_ms?: number | null;
        };
        /** AudioSessionOut */
        AudioSessionOut: {
            /** Status */
            status: string;
            /** Audio Format */
            audio_format: string;
            /** Received Count */
            received_count: number;
            /** Last Sequence */
            last_sequence: number | null;
            /** Next Sequence */
            next_sequence: number;
            /** Next Timestamp Ms */
            next_timestamp_ms: number;
            /** Missing Sequences */
            missing_sequences: number[];
            /** Received Duration Ms */
            received_duration_ms: number;
            /** Gaps */
            gaps: components["schemas"]["AudioGapOut"][];
            /** Reported Gap Reasons */
            reported_gap_reasons: string[];
            /** Purge Status */
            purge_status: string;
            /** Finalized At */
            finalized_at: string | null;
            /** Purged At */
            purged_at: string | null;
            /** Last Received At */
            last_received_at: string | null;
        };
        /** AuditEventOut */
        AuditEventOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Action */
            action: string;
            /** Entity Type */
            entity_type: string;
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Actor User Id */
            actor_user_id: string | null;
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
        };
        /** ChunkReceiptOut */
        ChunkReceiptOut: {
            /** Sequence */
            sequence: number;
            /**
             * Status
             * @enum {string}
             */
            status: "stored" | "duplicate";
        };
        /** ClaimOut */
        ClaimOut: {
            /** Section */
            section: string;
            /** Text */
            text: string;
            /** Fact Ids */
            fact_ids: string[];
            /** Warning Codes */
            warning_codes: string[];
        };
        /** ClientConfigOut */
        ClientConfigOut: {
            /** Environment */
            environment: string;
            /** Audio Format */
            audio_format: string;
            /** Sample Rate */
            sample_rate: number;
            /** Chunk Duration Ms */
            chunk_duration_ms: number;
            /** Max Chunk Bytes */
            max_chunk_bytes: number;
            /** Max Session Minutes */
            max_session_minutes: number;
            /** Warn Session Minutes */
            warn_session_minutes: number;
            /**
             * Patient Information Mode
             * @enum {string}
             */
            patient_information_mode: "none" | "confirm";
            /** Test Audio Source Enabled */
            test_audio_source_enabled: boolean;
        };
        /** ClinicalEncounter */
        ClinicalEncounter: {
            /** Encounter Id */
            encounter_id: string;
            /** Patient Id */
            patient_id: string;
            /** Practitioner Id */
            practitioner_id: string;
            /** Started At */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "recording" | "paused" | "finalizing" | "processing" | "review" | "validated" | "exported" | "archived" | "audio_error" | "upload_interrupted" | "transcription_failed" | "generation_failed";
            /** Object Version */
            object_version: number;
            /** Facts */
            facts: components["schemas"]["ClinicalFact"][];
            treatment_plan: components["schemas"]["TreatmentPlan"] | null;
            /** Procedures */
            procedures: components["schemas"]["Procedure"][];
            /** Warnings */
            warnings: components["schemas"]["EncounterWarning"][];
        };
        /** ClinicalFact */
        ClinicalFact: {
            /** Fact Id */
            fact_id: string;
            /**
             * Category
             * @enum {string}
             */
            category: "chief_complaint" | "history" | "symptom" | "clinical_finding" | "radiographic_finding" | "assessment" | "diagnosis" | "treatment_option" | "treatment_decision" | "procedure" | "material" | "medication" | "patient_information" | "follow_up" | "other";
            /** Concept */
            concept: string;
            /** Value */
            value: unknown;
            /** Teeth */
            teeth: string[];
            /** Surfaces */
            surfaces: ("M" | "D" | "O" | "V" | "B" | "L" | "P" | "I" | "C")[];
            /**
             * Assertion
             * @enum {string}
             */
            assertion: "present" | "absent" | "uncertain";
            /**
             * Temporality
             * @enum {string}
             */
            temporality: "past" | "current" | "future";
            /**
             * Clinical Status
             * @enum {string}
             */
            clinical_status: "patient_reported" | "observed" | "clinician_assessment" | "differential" | "discussed" | "proposed" | "accepted" | "refused" | "deferred" | "planned" | "performed";
            /**
             * Speaker Role
             * @enum {string}
             */
            speaker_role: "practitioner" | "patient" | "assistant" | "companion" | "unknown" | "manual";
            /**
             * Certainty
             * @enum {string}
             */
            certainty: "certain" | "probable" | "possible" | "unknown";
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "audio" | "manual" | "prior_record" | "system_test";
            /** Evidence Segment Ids */
            evidence_segment_ids: string[];
            /** Confidence */
            confidence: number;
            /** Manually Validated */
            manually_validated: boolean;
        };
        /** ClinicalObjectOut */
        ClinicalObjectOut: {
            clinical_object: components["schemas"]["ClinicalEncounter"];
            /** Versions */
            versions: components["schemas"]["ObjectVersionOut"][];
        };
        /** CorrectionRequest */
        CorrectionRequest: {
            /** Expected Object Version */
            expected_object_version: number;
            /** Operations */
            operations: (components["schemas"]["ReplaceTooth"] | components["schemas"]["UpdateFact"] | components["schemas"]["SetPlanItemStatus"] | components["schemas"]["AddFact"] | components["schemas"]["RemoveFact"])[];
            /**
             * Regenerate
             * @default true
             */
            regenerate: boolean;
        };
        /** DocumentOut */
        DocumentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Encounter Id
             * Format: uuid
             */
            encounter_id: string;
            /**
             * Document Type
             * @enum {string}
             */
            document_type: "consultation_note" | "treatment_plan_text" | "operative_note" | "patient_summary" | "referral_letter";
            /**
             * Status
             * @enum {string}
             */
            status: "draft_ai" | "needs_review" | "validated" | "exported" | "superseded" | "outdated";
            /** Version */
            version: number;
            /** Generated From Object Version */
            generated_from_object_version: number;
            /** Is Current */
            is_current: boolean;
            /** Content */
            content: string;
            /** Claims */
            claims: components["schemas"]["ClaimOut"][];
            /** Supported Fact Ids */
            supported_fact_ids: string[];
            /** Validation Issues */
            validation_issues: components["schemas"]["ValidationIssueOut"][];
            /** Generator */
            generator: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Validated At */
            validated_at: string | null;
        };
        /** DocumentSummary */
        DocumentSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Document Type
             * @enum {string}
             */
            document_type: "consultation_note" | "treatment_plan_text" | "operative_note" | "patient_summary" | "referral_letter";
            /**
             * Status
             * @enum {string}
             */
            status: "draft_ai" | "needs_review" | "validated" | "exported" | "superseded" | "outdated";
        };
        /** DocumentValidate */
        DocumentValidate: {
            /**
             * Acknowledged Warning Codes
             * @default []
             */
            acknowledged_warning_codes: string[];
        };
        /** EncounterCreate */
        EncounterCreate: {
            /**
             * Patient Id
             * Format: uuid
             */
            patient_id: string;
            /** Synthetic Case Id */
            synthetic_case_id?: string | null;
            /**
             * Shadow
             * @default false
             */
            shadow: boolean;
        };
        /** EncounterFinish */
        EncounterFinish: {
            /** Final Sequence */
            final_sequence?: number | null;
            /** Client Recorded Ms */
            client_recorded_ms?: number | null;
            /**
             * Accept Gaps
             * @default false
             */
            accept_gaps: boolean;
        };
        /** EncounterOut */
        EncounterOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            patient: components["schemas"]["PatientOut"];
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "recording" | "paused" | "finalizing" | "processing" | "review" | "validated" | "exported" | "archived" | "audio_error" | "upload_interrupted" | "transcription_failed" | "generation_failed";
            /** Object Version */
            object_version: number;
            /** Started At */
            started_at: string | null;
            /** Ended At */
            ended_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Synthetic Case Id */
            synthetic_case_id: string | null;
            /** Mode */
            mode: string;
            /** Processing Errors */
            processing_errors: components["schemas"]["ProcessingError"][];
            /** Critical Warning Count */
            critical_warning_count: number;
            /** Documents */
            documents: components["schemas"]["DocumentSummary"][];
        };
        /** EncounterStart */
        EncounterStart: {
            /**
             * Patient Informed
             * @default false
             */
            patient_informed: boolean;
        };
        /** EncounterWarning */
        EncounterWarning: {
            /** Code */
            code: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "review" | "critical";
            /** Message */
            message: string;
        };
        /** FactChanges */
        FactChanges: {
            /** Assertion */
            assertion?: ("present" | "absent" | "uncertain") | null;
            /** Temporality */
            temporality?: ("past" | "current" | "future") | null;
            /** Clinical Status */
            clinical_status?: ("patient_reported" | "observed" | "clinician_assessment" | "differential" | "discussed" | "proposed" | "accepted" | "refused" | "deferred" | "planned" | "performed") | null;
            /** Certainty */
            certainty?: ("certain" | "probable" | "possible" | "unknown") | null;
            /** Teeth */
            teeth?: string[] | null;
            /** Value */
            value?: unknown;
        };
        /** GlossaryTermOut */
        GlossaryTermOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Canonical */
            canonical: string;
            /** Aliases */
            aliases: string[];
            /** Category */
            category: string;
            /** Origin */
            origin: string;
            /** Status */
            status: string;
            /** Frequency */
            frequency: number;
        };
        /** GlossaryTermPatch */
        GlossaryTermPatch: {
            /** Canonical */
            canonical?: string | null;
            /** Aliases */
            aliases?: string[] | null;
            /** Status */
            status?: ("active" | "disabled") | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /**
             * Service
             * @constant
             */
            service: "oris-api";
            /** Version */
            version: string;
            /**
             * Environment
             * @enum {string}
             */
            environment: "local" | "test" | "staging" | "production";
            providers: components["schemas"]["ProviderStatus"];
        };
        /** LearningEventOut */
        LearningEventOut: {
            /**
             * Learning Event Id
             * Format: uuid
             */
            learning_event_id: string;
            /**
             * Event Type
             * @enum {string}
             */
            event_type: "transcript_word_correction" | "tooth_number_correction" | "speaker_role_correction" | "clinical_fact_added" | "clinical_fact_removed" | "clinical_fact_corrected" | "negation_correction" | "temporality_correction" | "certainty_correction" | "treatment_status_correction" | "treatment_sequence_correction" | "procedure_type_correction" | "material_name_correction" | "document_text_edit" | "document_section_deleted" | "document_section_added" | "warning_confirmed" | "warning_dismissed" | "glossary_term_added" | "style_preference_detected" | "document_validated_unchanged" | "document_validated_after_minor_edit" | "document_validated_after_major_edit" | "generation_rejected";
            /** Scope */
            scope: string;
            /** Source Version */
            source_version: string;
            /** Before */
            before: unknown;
            /** After */
            after: unknown;
            /** Confidence Before */
            confidence_before: number | null;
            /** Validated By Practitioner */
            validated_by_practitioner: boolean;
            /** Eligible For Global Learning */
            eligible_for_global_learning: boolean;
            /** Learning Status */
            learning_status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** NewFact */
        NewFact: {
            /**
             * Category
             * @enum {string}
             */
            category: "chief_complaint" | "history" | "symptom" | "clinical_finding" | "radiographic_finding" | "assessment" | "diagnosis" | "treatment_option" | "treatment_decision" | "procedure" | "material" | "medication" | "patient_information" | "follow_up" | "other";
            /** Concept */
            concept: string;
            /** Value */
            value: unknown;
            /**
             * Teeth
             * @default []
             */
            teeth: string[];
            /**
             * Surfaces
             * @default []
             */
            surfaces: ("M" | "D" | "O" | "V" | "B" | "L" | "P" | "I" | "C")[];
            /**
             * Assertion
             * @enum {string}
             */
            assertion: "present" | "absent" | "uncertain";
            /**
             * Temporality
             * @enum {string}
             */
            temporality: "past" | "current" | "future";
            /**
             * Clinical Status
             * @enum {string}
             */
            clinical_status: "patient_reported" | "observed" | "clinician_assessment" | "differential" | "discussed" | "proposed" | "accepted" | "refused" | "deferred" | "planned" | "performed";
            /**
             * Certainty
             * @enum {string}
             */
            certainty: "certain" | "probable" | "possible" | "unknown";
        };
        /** NewGlossaryTerm */
        NewGlossaryTerm: {
            /** Canonical */
            canonical: string;
            /**
             * Aliases
             * @default []
             */
            aliases: string[];
            /**
             * Category
             * @default other
             */
            category: string;
        };
        /** ObjectVersionOut */
        ObjectVersionOut: {
            /** Version */
            version: number;
            /** Change Kind */
            change_kind: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string | null;
        };
        /** PatientCreate */
        PatientCreate: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Birth Date */
            birth_date?: string | null;
            /** External Id */
            external_id?: string | null;
        };
        /** PatientOut */
        PatientOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Birth Date */
            birth_date: string | null;
            /** External Id */
            external_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PatientUpdate */
        PatientUpdate: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Birth Date */
            birth_date?: string | null;
            /** External Id */
            external_id?: string | null;
        };
        /**
         * PractitionerPreferences
         * @description Ce que le praticien a choisi. Les valeurs par défaut sont celles d'Oris.
         */
        PractitionerPreferences: {
            /**
             * Document Length
             * @default standard
             * @enum {string}
             */
            document_length: "standard" | "concise";
            /** Terminology */
            terminology?: {
                [key: string]: string;
            };
        };
        /**
         * PreferencesPatch
         * @description Modification partielle : seuls les champs fournis changent.
         */
        PreferencesPatch: {
            /** Document Length */
            document_length?: ("standard" | "concise") | null;
            /** Terminology */
            terminology?: {
                [key: string]: string;
            } | null;
        };
        /** Procedure */
        Procedure: {
            /** Procedure Id */
            procedure_id: string;
            /**
             * Procedure Type
             * @enum {string}
             */
            procedure_type: "composite" | "direct_aesthetic" | "veneer_preparation" | "veneer_bonding" | "wear_additive" | "extraction" | "minor_surgery_generic";
            /**
             * Status
             * @enum {string}
             */
            status: "planned" | "performed" | "cancelled";
            /** Teeth */
            teeth: string[];
            /** Structured Data */
            structured_data: {
                [key: string]: unknown;
            };
            /** Evidence Fact Ids */
            evidence_fact_ids: string[];
        };
        /** ProcessingError */
        ProcessingError: {
            /** Rule */
            rule: string;
            /** Subject Id */
            subject_id: string;
        };
        /**
         * ProgressOut
         * @description Avancement réel du traitement : chaque nombre est lu en base (S06).
         */
        ProgressOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "recording" | "paused" | "finalizing" | "processing" | "review" | "validated" | "exported" | "archived" | "audio_error" | "upload_interrupted" | "transcription_failed" | "generation_failed";
            /** Transcript Segments */
            transcript_segments: number;
            /** Facts */
            facts: number;
            /** Documents */
            documents: number;
            /** Termine */
            termine: boolean;
        };
        /** ProviderStatus */
        ProviderStatus: {
            /** Speech To Text */
            speech_to_text: string;
            /** Clinical Extraction */
            clinical_extraction: string;
            /** Document Generation */
            document_generation: string;
            /** Clinical Validation */
            clinical_validation: string;
        };
        /** PurgeReportOut */
        PurgeReportOut: {
            /** Purged */
            purged: string[];
            /** Failed */
            failed: string[];
            /** Remaining */
            remaining: number;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "unavailable";
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unreachable";
        };
        /** RemoveFact */
        RemoveFact: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            operation: "remove_fact";
            /** Fact Id */
            fact_id: string;
        };
        /**
         * ReplaceTooth
         * @description « Remplace 26 par 27 » : faits ciblés (tous si omis), plan et actes liés.
         */
        ReplaceTooth: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            operation: "replace_tooth";
            /** From Tooth */
            from_tooth: string;
            /** To Tooth */
            to_tooth: string;
            /** Fact Ids */
            fact_ids?: string[] | null;
        };
        /** SetPlanItemStatus */
        SetPlanItemStatus: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            operation: "set_plan_item_status";
            /** Item Id */
            item_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "discussed" | "proposed" | "accepted" | "refused" | "deferred" | "planned" | "completed";
        };
        /**
         * SpokenCorrectionOut
         * @description Ce qu'Oris a compris, et ce qu'il a fait — ou pas.
         */
        SpokenCorrectionOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "clinical" | "editorial" | "unclear";
            /** Summary */
            summary: string;
            /**
             * Impact
             * @enum {string}
             */
            impact: "normal" | "high";
            /** Reason */
            reason: string;
            /** Candidates */
            candidates: string[];
            /** Operations */
            operations: {
                [key: string]: unknown;
            }[];
            /** Applied */
            applied: boolean;
            /** Object Version */
            object_version: number;
        };
        /**
         * SpokenCorrectionRequest
         * @description Correction dictée ou écrite. Par défaut : aperçu, sans rien modifier.
         */
        SpokenCorrectionRequest: {
            /** Command */
            command: string;
            /** Expected Object Version */
            expected_object_version?: number | null;
            /**
             * Apply
             * @default false
             */
            apply: boolean;
        };
        /** SuggestionOut */
        SuggestionOut: {
            /** Key */
            key: string;
            /** Kind */
            kind: string;
            /** Message */
            message: string;
            /** Occurrences */
            occurrences: number;
            /** Payload */
            payload: {
                [key: string]: string;
            };
        };
        /** SyntheticCaseOut */
        SyntheticCaseOut: {
            /** Case Id */
            case_id: string;
            /** Domain */
            domain: string;
            /** Tags */
            tags: string[];
            /** Patient First Name */
            patient_first_name: string;
            /** Patient Last Name */
            patient_last_name: string;
            /** Segment Count */
            segment_count: number;
        };
        /** TranscriptOut */
        TranscriptOut: {
            /**
             * Encounter Id
             * Format: uuid
             */
            encounter_id: string;
            /** Segments */
            segments: components["schemas"]["TranscriptSegment"][];
        };
        /** TranscriptSegment */
        TranscriptSegment: {
            /** Segment Id */
            segment_id: string;
            /** Start Ms */
            start_ms: number;
            /** End Ms */
            end_ms: number;
            /**
             * Speaker Role
             * @enum {string}
             */
            speaker_role: "practitioner" | "patient" | "assistant" | "companion" | "unknown";
            /** Text */
            text: string;
            /** Confidence */
            confidence: number;
            /** Is Final */
            is_final: boolean;
        };
        /** TreatmentPlan */
        TreatmentPlan: {
            /** Plan Id */
            plan_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "review" | "validated" | "superseded";
            /** Goals */
            goals: string[];
            /** Notes */
            notes: string[];
            /** Items */
            items: components["schemas"]["TreatmentPlanItem"][];
        };
        /** TreatmentPlanItem */
        TreatmentPlanItem: {
            /** Item Id */
            item_id: string;
            /** Teeth */
            teeth: string[];
            /** Problem */
            problem: string | null;
            /** Action */
            action: string;
            /**
             * Status
             * @enum {string}
             */
            status: "discussed" | "proposed" | "accepted" | "refused" | "deferred" | "planned" | "completed";
            /**
             * Priority
             * @enum {string}
             */
            priority: "urgent" | "high" | "routine" | "low" | "unspecified";
            /** Sequence */
            sequence: number | null;
            /** Alternatives */
            alternatives: string[];
            /** Prerequisites */
            prerequisites: string[];
            /** Uncertainties */
            uncertainties: string[];
            /** Evidence Fact Ids */
            evidence_fact_ids: string[];
        };
        /** UpdateFact */
        UpdateFact: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            operation: "update_fact";
            /** Fact Id */
            fact_id: string;
            changes: components["schemas"]["FactChanges"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValidationIssueOut */
        ValidationIssueOut: {
            /** Code */
            code: string;
            /** Severity */
            severity: string;
            /** Fact Id */
            fact_id: string | null;
            /** Claim Index */
            claim_index: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    list_patients_patients_get: {
        parameters: {
            query?: {
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_patient_patients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_patient_patients__patient_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_patient_patients__patient_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_encounters_encounters_get: {
        parameters: {
            query?: {
                status?: ("draft" | "recording" | "paused" | "finalizing" | "processing" | "review" | "validated" | "exported" | "archived" | "audio_error" | "upload_interrupted" | "transcription_failed" | "generation_failed") | null;
                patient_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_encounter_encounters_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EncounterCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_encounter_encounters__encounter_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_encounters__encounter_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["EncounterStart"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_encounters__encounter_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_encounters__encounter_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finish_encounters__encounter_id__finish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["EncounterFinish"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_progress_encounters__encounter_id__progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_encounters__encounter_id__process_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_encounter_encounters__encounter_id__validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transcript_encounters__encounter_id__transcript_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clinical_object_encounters__encounter_id__clinical_object_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClinicalObjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_clinical_object_encounters__encounter_id__clinical_object_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_from_speech_encounters__encounter_id__corrections_text_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpokenCorrectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpokenCorrectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_from_voice_encounters__encounter_id__corrections_voice_post: {
        parameters: {
            query?: {
                apply?: boolean;
                expected_object_version?: number | null;
            };
            header: {
                "content-type": string;
            };
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "audio/pcm;rate=16000;channels=1;encoding=s16le": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpokenCorrectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_encounters__encounter_id__documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_documents_encounters__encounter_id__documents_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_operative_note_encounters__encounter_id__documents_operative_note_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_document_documents__document_id__validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentValidate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_document_documents__document_id__export_get: {
        parameters: {
            query?: {
                format?: "pdf" | "text" | "structured";
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                    "text/plain": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    learning_events_encounters__encounter_id__learning_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cases_synthetic_cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyntheticCaseOut"][];
                };
            };
        };
    };
    run_case_synthetic_cases__case_id__encounters_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_chunk_encounters__encounter_id__audio_chunks__sequence__put: {
        parameters: {
            query?: never;
            header: {
                "content-type": string;
                "x-chunk-timestamp-ms": number;
                "x-chunk-checksum": string;
            };
            path: {
                encounter_id: string;
                sequence: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "audio/pcm;rate=16000;channels=1;encoding=s16le": string;
            };
        };
        responses: {
            /** @description Segment déjà reçu à l'identique */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkReceiptOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_gap_encounters__encounter_id__audio_gaps_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AudioGapReport"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudioSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audio_encounters__encounter_id__audio_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudioSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    client_config_config_client_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientConfigOut"];
                };
            };
        };
    };
    read_concepts_ontology_concepts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    read_preferences_me_preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PractitionerPreferences"];
                };
            };
        };
    };
    patch_preferences_me_preferences_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PractitionerPreferences"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_glossary_glossary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossaryTermOut"][];
                };
            };
        };
    };
    add_glossary_term_glossary_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewGlossaryTerm"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossaryTermOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_glossary_term_glossary__term_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                term_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GlossaryTermPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossaryTermOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_suggestions_me_learning_suggestions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionOut"][];
                };
            };
        };
    };
    read_audit_audit_get: {
        parameters: {
            query?: {
                encounter_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_audio_purge_maintenance_audio_purge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurgeReportOut"];
                };
            };
        };
    };
}
